services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"

    networks:
      - backend-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mqtt:
    image: hivemq/hivemq4
    ports:
      - "8080:8080"
      - "1883:1883"
    networks:
      - backend-network

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "7000:7000"

    depends_on:
      - db
      - mqtt

    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - backend-network

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - be

    volumes:
      - ./fe/:/app/

    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
